name: env-fluidsim-mpi
dependencies:
  - fluidsim
  - openmpi
  - h5py=*=mpi*
  - ffmpeg=7.1.0
  - ffmpeg-python=0.2.0
  - fluidfft-fftw
  - fluidfft-fftwmpi
  - fluidfft-mpi_with_fftw
  - ipython
  - matplotlib
